"""Tracker data convertion

Revision ID: db81666a733a
Revises: f0a23b50ffbf
Create Date: 2025-03-11 01:42:49.896305

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db81666a733a"
down_revision: Union[str, None] = "f0a23b50ffbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leaderboard_tracker", schema=None) as batch_op:
        batch_op.drop_column("data")
        batch_op.add_column(sa.Column("data", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leaderboard_tracker", schema=None) as batch_op:
        batch_op.drop_column("data")
        batch_op.add_column(sa.Column("data", sa.VARCHAR(length=500), nullable=False))
    # ### end Alembic commands ###
